namespace Nexaflow.Visuals.Icons;

/// <summary>
/// The emoji offered as icons, each with the name it is shown by and the extra words it is found by. Names and
/// keywords are search terms, matched in English whatever the UI language, like the Fluent names beside them.
/// </summary>
internal static class EmojiIcons
{
    private static readonly (string Glyph, string Name, string Keywords)[] Table =
    [
        ("🖥", "desktop computer", "screen monitor pc display"),
        ("💻", "laptop", "computer notebook pc"),
        ("📱", "mobile phone", "smartphone device"),
        ("⌨", "keyboard", "type input"),
        ("🖱", "mouse", "pointer click"),
        ("🖨", "printer", "print"),
        ("📁", "folder", "files directory"),
        ("📂", "open folder", "files directory"),
        ("💾", "floppy disk", "save"),
        ("💿", "disc", "cd dvd optical"),
        ("🗂", "card dividers", "organise tabs index"),
        ("🗃", "card file box", "archive records"),
        ("📦", "package", "box archive parcel"),
        ("🗜", "clamp", "compress zip squeeze"),
        ("📄", "page", "document file"),
        ("📝", "memo", "note write edit"),
        ("📋", "clipboard", "paste copy"),
        ("🗒", "notepad", "notes list"),
        ("📎", "paperclip", "attach"),
        ("📌", "pushpin", "pin"),
        ("📍", "round pin", "location place"),
        ("✂", "scissors", "cut"),
        ("🖊", "pen", "write"),
        ("🖋", "fountain pen", "write sign"),
        ("✒", "nib", "pen write"),
        ("🖌", "paintbrush", "paint art"),
        ("🖍", "crayon", "draw"),
        ("🖼", "framed picture", "image photo art"),
        ("📐", "set square", "ruler geometry"),
        ("📏", "ruler", "measure"),
        ("🧮", "abacus", "calculator maths count"),
        ("🔍", "magnifier", "search find zoom"),
        ("🔎", "magnifier right", "search find zoom"),
        ("🔬", "microscope", "inspect science"),
        ("🔭", "telescope", "explore astronomy"),
        ("📡", "satellite dish", "antenna network signal"),
        ("🛰", "satellite", "space orbit"),
        ("🌐", "globe", "web internet world"),
        ("🗺", "map", "world atlas"),
        ("🔗", "link", "url chain"),
        ("💬", "speech bubble", "chat message talk"),
        ("🗨", "comment", "speech chat"),
        ("🗯", "shout", "speech angry"),
        ("📢", "loudspeaker", "announce public"),
        ("📣", "megaphone", "announce cheer"),
        ("🔔", "bell", "notification alert"),
        ("🔕", "bell off", "mute silent"),
        ("📯", "horn", "post"),
        ("📬", "mailbox", "mail email letter"),
        ("📤", "outbox", "upload send"),
        ("📥", "inbox", "download receive"),
        ("🎵", "musical note", "music audio song"),
        ("🎶", "musical notes", "music audio song"),
        ("🎙", "microphone", "record voice podcast"),
        ("🎚", "level slider", "volume audio"),
        ("🎛", "control knobs", "mixer audio"),
        ("📺", "television", "tv video screen"),
        ("📻", "radio", "audio broadcast"),
        ("🎬", "clapper board", "video film movie"),
        ("📠", "fax", "machine"),
        ("📟", "pager", "beeper"),
        ("🕹", "joystick", "game arcade"),
        ("🎮", "game controller", "gamepad play"),
        ("⚙", "gear", "settings cog options"),
        ("🔧", "wrench", "tools fix settings"),
        ("🔨", "hammer", "build tools"),
        ("🪛", "screwdriver", "tools fix"),
        ("🔩", "nut and bolt", "hardware"),
        ("🪝", "hook", "hang"),
        ("🧰", "toolbox", "tools kit"),
        ("🪜", "ladder", "climb"),
        ("🧲", "magnet", "attract"),
        ("💡", "light bulb", "idea tip"),
        ("🔋", "battery", "power charge"),
        ("🔌", "plug", "power electric"),
        ("⌚", "watch", "time clock"),
        ("🗓", "spiral calendar", "date schedule"),
        ("📅", "calendar", "date schedule"),
        ("📆", "tear-off calendar", "date day"),
        ("🗑", "wastebasket", "trash delete bin recycle"),
        ("🧳", "luggage", "suitcase travel"),
        ("🏠", "house", "home"),
        ("🏢", "office building", "work company"),
        ("🏗", "construction", "build crane"),
        ("🏭", "factory", "industry"),
        ("🏦", "bank", "money finance"),
        ("🏥", "hospital", "health"),
        ("🏛", "classical building", "museum government"),
        ("🎓", "graduation cap", "learn school education"),
        ("🏆", "trophy", "win award"),
        ("⭐", "star", "favourite favorite"),
        ("🌟", "glowing star", "favourite shine"),
        ("💫", "dizzy", "sparkle"),
        ("⚡", "lightning", "fast power zap"),
        ("🔥", "fire", "hot flame"),
        ("❤", "red heart", "love like"),
        ("💙", "blue heart", "love like"),
        ("💚", "green heart", "love like"),
        ("💛", "yellow heart", "love like"),
        ("🟥", "red square", "colour"),
        ("🟦", "blue square", "colour"),
        ("🟩", "green square", "colour"),
        ("🟨", "yellow square", "colour"),
        ("⬛", "black square", "colour"),
        ("⬜", "white square", "colour"),
        ("➕", "plus", "add new"),
        ("➖", "minus", "remove subtract"),
        ("✖", "multiply", "close times"),
        ("➗", "divide", "division"),
        ("🟰", "equals", "equal"),
        ("✅", "check mark", "done tick yes ok"),
        ("❌", "cross mark", "cancel no close"),
        ("⚠", "warning", "caution alert"),
        ("ℹ", "information", "info help"),
        ("🔒", "locked", "lock secure private"),
        ("🔓", "unlocked", "unlock open"),
        ("👤", "person", "user account profile"),
        ("👥", "people", "users group team"),
        ("🤖", "robot", "ai bot assistant"),
        ("🐛", "bug", "debug insect"),
        ("🦋", "butterfly", "insect"),
    ];

    public static IReadOnlyList<IconEntry> All { get; } =
        Table.Select(e => new IconEntry(IconRef.Emoji(e.Glyph), e.Name, e.Keywords, e.Glyph)).ToList();
}
