using System;
using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using Nexaflow.Tests.Fixtures;
using Nexaflow.Visuals.Text.Markdown;
using Nexaflow.Visuals.Text.Markdown.WordCloud;

namespace Nexaflow.Tests.Visuals.Markdown.WordCloud;

/// <summary>
/// Writes the word-cloud figures for the user documentation, through the real builder so the picture in the
/// docs is the picture the app draws. Opt-in: set <c>NEXAFLOW_WRITE_FIGURES</c> to the output folder.
/// </summary>
[TestClass]
[TestCategory("UI")]
[NoCoverage("writes a documentation figure")]
public class WordCloudFigureWriter
{
    /// <summary>What the help page shows first: a plain cloud, with nothing set but the words.</summary>
    private const string Figure = """
        design: 900
        system: 517
        colour: 374
        layout: 297
        type: 248
        grid: 215
        space: 190
        scale: 171
        contrast: 155
        rhythm: 143
        balance: 132
        texture: 123
        pattern: 116
        shape: 109
        line: 103
        form: 98
        hierarchy: 93
        alignment: 89
        proximity: 85
        typography: 82
        serif: 79
        kerning: 76
        leading: 73
        baseline: 71
        ligature: 69
        glyph: 66
        italic: 64
        roman: 63
        caption: 61
        heading: 59
        palette: 58
        hue: 56
        saturation: 55
        tone: 54
        tint: 52
        accent: 51
        neutral: 50
        gradient: 49
        opacity: 48
        shadow: 47
        canvas: 46
        margin: 45
        gutter: 44
        column: 44
        module: 43
        template: 42
        mockup: 41
        prototype: 41
        wireframe: 40
        sketch: 39
        draft: 39
        revision: 38
        proof: 38
        render: 37
        export: 36
        asset: 36
        artboard: 35
        layer: 35
        mask: 34
        motion: 34
        easing: 34
        timing: 33
        transition: 33
        duration: 32
        spring: 32
        bounce: 32
        fade: 31
        slide: 31
        rotate: 30
        parallax: 30
        keyframe: 30
        curve: 29
        anticipation: 29
        overlap: 29
        stagger: 28
        brand: 28
        identity: 28
        logo: 28
        mark: 27
        voice: 27
        story: 27
        message: 26
        audience: 26
        context: 26
        craft: 26
        detail: 26
        polish: 25
        restraint: 25
        clarity: 25
        intent: 25
        constraint: 24
        tradeoff: 24
        iteration: 24
        critique: 24
        legible: 24
        readable: 23
        focus: 23
        label: 23
        landmark: 23
        ratio: 23
        target: 22
        keyboard: 22
        screen: 22
        reader: 22
        print: 22
        mobile: 22
        tablet: 21
        desktop: 21
        viewport: 21
        breakpoint: 21
        responsive: 21
        fluid: 21
        adaptive: 21
        container: 20
        stack: 20
        flow: 20
        wrap: 20
        snap: 20
        anchor: 20
        offset: 20
        """;


    /// <summary>
    /// A shape, turned words and colours written out. Deliberately long: a shape is not a boundary — the words
    /// simply run out where the outline is — so it takes a couple of hundred of them before one reads as a star.
    /// </summary>
    private const string Shaped = """
        shape: star
        ellipticity: 1
        width: 760
        height: 700
        minSize: 6
        maxSize: 88
        scale: log
        gap: 1
        rotate: 0.15
        color: #b5304a #d1793f #3f7fb5 #4f9c6b #7a4fa3
        weather: 1200
        rain: 714
        cloud: 526
        wind: 424
        storm: 359
        frost: 313
        mist: 279
        snow: 252
        thunder: 231
        sunshine: 213
        drizzle: 199
        shower: 186
        gale: 175
        breeze: 166
        fog: 157
        hail: 150
        sleet: 143
        lightning: 137
        rainbow: 132
        overcast: 127
        pressure: 122
        front: 118
        isobar: 114
        forecast: 111
        warning: 107
        flood: 104
        drought: 101
        humid: 99
        muggy: 96
        crisp: 94
        chill: 91
        thaw: 89
        freeze: 87
        melt: 85
        damp: 83
        dry: 82
        bright: 80
        dull: 78
        grey: 77
        blue: 75
        morning: 74
        evening: 73
        night: 71
        dawn: 70
        dusk: 69
        noon: 68
        season: 67
        spring: 66
        summer: 65
        autumn: 64
        winter: 63
        monsoon: 62
        cyclone: 61
        hurricane: 60
        tornado: 59
        blizzard: 59
        squall: 58
        swell: 57
        tide: 56
        current: 56
        coast: 55
        moor: 54
        valley: 54
        ridge: 53
        summit: 52
        plain: 52
        estuary: 51
        channel: 51
        strait: 50
        bay: 50
        temperature: 49
        degrees: 49
        celsius: 48
        minimum: 48
        maximum: 47
        average: 47
        record: 46
        anomaly: 46
        trend: 45
        pattern: 45
        satellite: 44
        radar: 44
        station: 44
        buoy: 43
        balloon: 43
        model: 42
        ensemble: 42
        hindcast: 42
        nowcast: 41
        outlook: 41
        space: 41
        orbit: 40
        launch: 40
        rocket: 40
        booster: 39
        payload: 39
        capsule: 39
        module: 39
        probe: 38
        lander: 38
        rover: 38
        flyby: 37
        transit: 37
        eclipse: 37
        comet: 37
        asteroid: 36
        meteor: 36
        nebula: 36
        galaxy: 36
        cluster: 35
        quasar: 35
        pulsar: 35
        supernova: 35
        redshift: 34
        parallax: 34
        spectrum: 34
        telescope: 34
        mirror: 34
        aperture: 33
        exposure: 33
        photon: 33
        neutrino: 33
        gravity: 32
        tidal: 32
        escape: 32
        velocity: 32
        apogee: 32
        perigee: 32
        inclination: 31
        trajectory: 31
        burn: 31
        thrust: 31
        stage: 31
        fairing: 30
        gimbal: 30
        telemetry: 30
        downlink: 30
        beacon: 30
        antenna: 30
        solar: 29
        panel: 29
        battery: 29
        cryogenic: 29
        propellant: 29
        oxidiser: 29
        plume: 29
        reentry: 28
        ablation: 28
        splashdown: 28
        lunar: 28
        martian: 28
        venusian: 28
        jovian: 28
        saturnian: 27
        kuiper: 27
        oort: 27
        heliosphere: 27
        corona: 27
        flare: 27
        observatory: 27
        survey: 27
        catalogue: 26
        ephemeris: 26
        occultation: 26
        albedo: 26
        regolith: 26
        crater: 26
        rille: 26
        mare: 26
        design: 25
        system: 25
        colour: 25
        layout: 25
        type: 25
        grid: 25
        scale: 25
        contrast: 25
        rhythm: 25
        balance: 25
        texture: 24
        shape: 24
        line: 24
        form: 24
        hierarchy: 24
        alignment: 24
        proximity: 24
        typography: 24
        serif: 24
        kerning: 24
        leading: 23
        baseline: 23
        ligature: 23
        glyph: 23
        italic: 23
        roman: 23
        caption: 23
        heading: 23
        palette: 23
        hue: 23
        saturation: 23
        tone: 22
        tint: 22
        accent: 22
        neutral: 22
        gradient: 22
        opacity: 22
        shadow: 22
        canvas: 22
        margin: 22
        gutter: 22
        column: 22
        template: 22
        mockup: 22
        prototype: 21
        wireframe: 21
        sketch: 21
        draft: 21
        revision: 21
        proof: 21
        render: 21
        export: 21
        asset: 21
        artboard: 21
        layer: 21
        mask: 21
        motion: 21
        easing: 21
        timing: 20
        transition: 20
        duration: 20
        bounce: 20
        fade: 20
        slide: 20
        rotate: 20
        keyframe: 20
        curve: 20
        anticipation: 20
        overlap: 20
        stagger: 20
        brand: 20
        identity: 20
        logo: 20
        mark: 19
        voice: 19
        story: 19
        message: 19
        audience: 19
        context: 19
        craft: 19
        detail: 19
        polish: 19
        restraint: 19
        clarity: 19
        intent: 19
        constraint: 19
        tradeoff: 19
        iteration: 19
        critique: 19
        legible: 19
        readable: 19
        focus: 18
        label: 18
        landmark: 18
        ratio: 18
        target: 18
        keyboard: 18
        screen: 18
        reader: 18
        print: 18
        mobile: 18
        tablet: 18
        desktop: 18
        viewport: 18
        breakpoint: 18
        responsive: 18
        fluid: 18
        adaptive: 18
        container: 18
        stack: 18
        flow: 18
        wrap: 17
        snap: 17
        anchor: 17
        offset: 17
        """;

    /// <summary>
    /// A cloud packed into letters. The words have to be small against the letters or there is nothing left of
    /// them to read, which is what `minSize:` and `maxSize:` are for.
    /// </summary>
    private const string Lettered = """
        letters: CLOUD
        width: 860
        height: 400
        minSize: 4
        maxSize: 30
        scale: log
        gridSize: 2
        gap: 1
        rotate: 0
        design: 900
        system: 594
        colour: 466
        layout: 392
        type: 343
        grid: 307
        space: 280
        scale: 258
        contrast: 241
        rhythm: 226
        balance: 214
        texture: 203
        pattern: 193
        shape: 185
        line: 177
        form: 171
        hierarchy: 164
        alignment: 159
        proximity: 154
        typography: 149
        serif: 145
        kerning: 141
        leading: 137
        baseline: 134
        ligature: 130
        glyph: 127
        italic: 125
        roman: 122
        caption: 119
        heading: 117
        palette: 115
        hue: 113
        saturation: 110
        tone: 108
        tint: 107
        accent: 105
        neutral: 103
        gradient: 101
        opacity: 100
        shadow: 98
        canvas: 97
        margin: 96
        gutter: 94
        column: 93
        module: 92
        template: 90
        mockup: 89
        prototype: 88
        wireframe: 87
        sketch: 86
        draft: 85
        revision: 84
        proof: 83
        render: 82
        export: 81
        asset: 80
        artboard: 80
        layer: 79
        mask: 78
        motion: 77
        easing: 76
        timing: 76
        transition: 75
        duration: 74
        spring: 74
        bounce: 73
        fade: 72
        slide: 72
        rotate: 71
        parallax: 70
        keyframe: 70
        curve: 69
        anticipation: 69
        overlap: 68
        stagger: 67
        brand: 67
        identity: 66
        logo: 66
        mark: 65
        voice: 65
        story: 64
        message: 64
        audience: 64
        context: 63
        craft: 63
        detail: 62
        polish: 62
        restraint: 61
        clarity: 61
        intent: 60
        constraint: 60
        tradeoff: 60
        iteration: 59
        critique: 59
        legible: 59
        readable: 58
        focus: 58
        label: 57
        landmark: 57
        ratio: 57
        target: 56
        keyboard: 56
        screen: 56
        reader: 55
        print: 55
        mobile: 55
        tablet: 55
        desktop: 54
        viewport: 54
        breakpoint: 54
        responsive: 53
        fluid: 53
        adaptive: 53
        container: 52
        stack: 52
        flow: 52
        wrap: 52
        snap: 51
        anchor: 51
        offset: 51
        weather: 51
        rain: 50
        cloud: 50
        wind: 50
        storm: 50
        frost: 49
        mist: 49
        snow: 49
        thunder: 49
        sunshine: 49
        drizzle: 48
        shower: 48
        gale: 48
        breeze: 48
        fog: 47
        hail: 47
        sleet: 47
        lightning: 47
        rainbow: 47
        overcast: 46
        pressure: 46
        front: 46
        isobar: 46
        forecast: 46
        warning: 45
        flood: 45
        drought: 45
        humid: 45
        muggy: 45
        crisp: 45
        chill: 44
        thaw: 44
        freeze: 44
        melt: 44
        damp: 44
        dry: 43
        bright: 43
        dull: 43
        grey: 43
        blue: 43
        morning: 43
        evening: 43
        night: 42
        dawn: 42
        dusk: 42
        noon: 42
        season: 42
        summer: 42
        autumn: 41
        winter: 41
        monsoon: 41
        cyclone: 41
        hurricane: 41
        tornado: 41
        blizzard: 41
        squall: 40
        swell: 40
        tide: 40
        current: 40
        coast: 40
        moor: 40
        valley: 40
        ridge: 40
        summit: 39
        plain: 39
        estuary: 39
        channel: 39
        strait: 39
        bay: 39
        temperature: 39
        degrees: 39
        celsius: 38
        minimum: 38
        maximum: 38
        average: 38
        record: 38
        anomaly: 38
        trend: 38
        satellite: 38
        radar: 37
        station: 37
        buoy: 37
        balloon: 37
        model: 37
        ensemble: 37
        hindcast: 37
        nowcast: 37
        outlook: 37
        orbit: 36
        launch: 36
        rocket: 36
        booster: 36
        payload: 36
        capsule: 36
        probe: 36
        lander: 36
        rover: 36
        flyby: 36
        transit: 35
        eclipse: 35
        comet: 35
        asteroid: 35
        meteor: 35
        nebula: 35
        galaxy: 35
        cluster: 35
        quasar: 35
        pulsar: 35
        supernova: 35
        redshift: 34
        spectrum: 34
        telescope: 34
        mirror: 34
        aperture: 34
        exposure: 34
        photon: 34
        neutrino: 34
        gravity: 34
        tidal: 34
        escape: 34
        velocity: 33
        apogee: 33
        perigee: 33
        inclination: 33
        trajectory: 33
        burn: 33
        thrust: 33
        stage: 33
        fairing: 33
        gimbal: 33
        telemetry: 33
        downlink: 33
        beacon: 33
        antenna: 32
        solar: 32
        panel: 32
        battery: 32
        cryogenic: 32
        propellant: 32
        oxidiser: 32
        plume: 32
        reentry: 32
        ablation: 32
        splashdown: 32
        lunar: 32
        martian: 32
        venusian: 32
        jovian: 31
        saturnian: 31
        kuiper: 31
        oort: 31
        heliosphere: 31
        corona: 31
        flare: 31
        observatory: 31
        survey: 31
        catalogue: 31
        ephemeris: 31
        occultation: 31
        albedo: 31
        regolith: 31
        crater: 30
        rille: 30
        mare: 30
        """;




    [TestMethod]
    public void WriteWordCloudFigure()
    {
        var folder = Environment.GetEnvironmentVariable("NEXAFLOW_WRITE_FIGURES");
        if (string.IsNullOrEmpty(folder)) Assert.Inconclusive("set NEXAFLOW_WRITE_FIGURES to write the figure");

        Directory.CreateDirectory(folder);

        UiThread.Run(() =>
        {
            Write(Path.Combine(folder, "wordcloud.png"), Figure, MarkdownPalette.Light, Brushes.White, 720);
            Write(Path.Combine(folder, "wordcloud-shapes.png"), Shaped, MarkdownPalette.Light, Brushes.White, 720);
            Write(Path.Combine(folder, "wordcloud-letters.png"), Lettered, MarkdownPalette.Light, Brushes.White, 900);
        });
    }

    private static void Write(string path, string source, MarkdownPalette palette, Brush ground, double width)
    {
        var host = new Border
        {
            Background = ground,
            Padding = new Thickness(16),
            Child = WordCloudBuilder.Element(source, DiagramRenderOptions.For(palette)),
        };

        host.Measure(new Size(width, double.PositiveInfinity));
        host.Arrange(new Rect(host.DesiredSize));
        host.UpdateLayout();

        var bitmap = new RenderTargetBitmap((int)Math.Ceiling(host.ActualWidth), (int)Math.Ceiling(host.ActualHeight),
                                            96, 96, PixelFormats.Pbgra32);
        bitmap.Render(host);

        var encoder = new PngBitmapEncoder();
        encoder.Frames.Add(BitmapFrame.Create(bitmap));

        using var file = File.Create(path);
        encoder.Save(file);
    }
}
