using System;
using System.IO;
using System.Linq;
using Nexaflow.Services.Initiatives.Graph;
using Nexaflow.Tests.Fixtures;

namespace Nexaflow.Tests.Initiatives.Graph;

/// <summary>
/// What <c>graph build</c> walks, and what it refuses to.
/// <para>
/// Written from a mutation run: every one of the ten entries in <c>RepoFiles.SkipDirs</c> could be blanked
/// to <c>""</c> and nothing went red. That set is the only thing standing between a graph build and
/// <c>node_modules</c>, so the failure mode is not a wrong answer — it is a build that takes minutes
/// instead of seconds and a graph full of dependency source nobody asked about. Nothing else in the suite
/// would have noticed.
/// </para>
/// </summary>
[TestClass]
[CoversNode("graph-build")]
public class RepoFilesTests
{
    private string _root = string.Empty;

    [TestInitialize]
    public void Setup() => _root = Directory.CreateTempSubdirectory("nexa-repofiles-").FullName;

    [TestCleanup]
    public void Teardown() { try { Directory.Delete(_root, recursive: true); } catch { } }

    private void Write(string relative, string content = "class C { }")
    {
        var full = Path.Combine(_root, relative.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(full)!);
        File.WriteAllText(full, content);
    }

    private string[] Source() =>
        [.. RepoFiles.EnumerateSource(_root, 1000).Select(p => Path.GetRelativePath(_root, p).Replace('\\', '/'))];

    [TestMethod]
    public void EveryNamedSkipDirectory_IsActuallySkipped()
    {
        // One file per skipped directory, all of them code, all of them findable if the set stops working.
        string[] skipped = [".git", ".claude", ".product", "bin", "obj", "node_modules", ".vs", ".idea",
                            "test-samples", "packages"];
        foreach (var dir in skipped) Write($"{dir}/Buried.cs");
        Write("src/Real.cs");

        var found = Source();

        CollectionAssert.AreEqual(new[] { "src/Real.cs" }, found,
            "a skipped directory that stops being skipped does not fail anything — it just makes every "
            + "graph build slower and noisier, one directory at a time:\n  " + string.Join("\n  ", found));
    }

    [TestMethod]
    public void ASkipNameNestedDeeper_IsSkippedThere_Too()
    {
        // The names are matched per directory segment, not just at the root: a feature's own bin/ is as
        // uninteresting as the top-level one, and there are ~60 of them in this repo.
        Write("src/Feature/obj/Debug/Generated.cs");
        Write("src/Feature/Real.cs");

        CollectionAssert.AreEqual(new[] { "src/Feature/Real.cs" }, Source());
    }

    [TestMethod]
    public void ADirectoryMerelyStartingWithASkipName_IsKept()
    {
        // "binding", not "bin". Matching on prefix rather than the whole segment would quietly drop real
        // source, which is the more expensive direction of this mistake.
        Write("src/binding/Real.cs");
        Write("src/objects/Also.cs");

        CollectionAssert.AreEquivalent(new[] { "src/binding/Real.cs", "src/objects/Also.cs" }, Source());
    }

    [TestMethod]
    public void AGeneratedFile_IsRecognisedByItsMarker_NotItsExtension()
    {
        // The 31 MB of tree-sitter parser.c tables are the reason this is a per-file test rather than an
        // unregistered extension: the hand-written scanner.c beside them is real source.
        Write("src/parser.c", "/* @generated by tree-sitter */\nint main() { }");
        Write("src/scanner.c", "int scan() { }");

        Assert.IsTrue(RepoFiles.IsGenerated(Path.Combine(_root, "src", "parser.c")));
        Assert.IsFalse(RepoFiles.IsGenerated(Path.Combine(_root, "src", "scanner.c")));
    }

    [TestMethod]
    public void EveryGeneratedMarkerConvention_IsHonoured()
    {
        var markers = new[]
        {
            ("tree-sitter", "// @generated"),
            ("roslyn",      "// <auto-generated />"),
            ("protobuf",    "// DO NOT EDIT"),
            ("prose",       "// This file was automatically generated"),
            ("prose2",      "// this code was generated by a tool"),
        };

        foreach (var (name, marker) in markers)
        {
            Write($"gen/{name}.cs", marker + "\nclass C { }");
            Assert.IsTrue(RepoFiles.IsGenerated(Path.Combine(_root, "gen", $"{name}.cs")),
                $"the {name} convention is in GeneratedMarkers and must keep working");
        }

        Write("gen/handwritten.cs", "// generated interest, but not generated code\nclass C { }");
        Assert.IsFalse(RepoFiles.IsGenerated(Path.Combine(_root, "gen", "handwritten.cs")));
    }

    [TestMethod]
    public void AMarkerBelowTheHeadOfTheFile_IsNotSearchedFor()
    {
        // Deliberate: only the head is read, because scanning a 31 MB table for a string it does not contain
        // is the exact cost this check exists to avoid. Pinned so "just scan the whole file" is a visible
        // decision rather than a quiet regression.
        Write("src/late.cs", new string(' ', 4096) + "\n// <auto-generated />\nclass C { }");

        Assert.IsFalse(RepoFiles.IsGenerated(Path.Combine(_root, "src", "late.cs")));
    }

    [TestMethod]
    public void AnUnreadableFile_IsNotTreatedAsGenerated()
    {
        Assert.IsFalse(RepoFiles.IsGenerated(Path.Combine(_root, "does-not-exist.cs")),
            "unreadable is not 'generated' — let the normal path report it");
    }
}
