<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Nexaflow.Tests.Features" />
    <InternalsVisibleTo Include="Nexaflow.Tests.IO" />
  </ItemGroup>

</Project>
